### ISSUE TITLE
Humidity sensors support 

### ISSUE THREAD

**Issue by allamiro** [bcl/digitemp#28]
are you guys planning on humidity sensors support or can this software support it ?
MS-TH - Temperature and Humidity Sensor

**Comment by bcl** [comment]
I'm pretty sure the MS-TH works. I haven't run a humidity sensor on my network in a while, it is a TAI-8540 from www.aag.com.mx (which no longer exists) so if the MS-TH is the same design it will work. Best thing to do is ask iButton, they've been great supporters of DigiTemp over the years and they will know for sure.
