### ISSUE TITLE
Can digitemp tell me the value of the "Read Power Supply [B4h]" command?

### ISSUE THREAD

**Issue by jaimet** [bcl/digitemp#29]
Hi.

The [DS18B20 datasheet](https://datasheets.maximintegrated.com/en/ds/DS18B20.pdf) makes several references to a "Read Power Supply [B4h]" command which can be used "to determine if any DS18B20s on the bus are using parasite power." (instead of, presumably, external power via Vdd).

Is there any way that I can get this information, for a given sensor, via digitemp?

(Thank you for writing digitemp, by the way - it's much appreciated. I've just built my first 1-wire network out of a CP2102, a couple of old cat5 patch leads and two DS18B20 digital thermometers, and it's working perfectly!)

Jaime

**Comment by bcl** [comment]
No, digitemp doesn't support that command. It's possible to add it, but then you have to add a way to display it that fits with the rest of the outputs. Normally I know if my 1-wire network is passive or not, and it's unusual to have individual sensors using different power modes.
