### ISSUE TITLE
How to use an USB adaptor?

### ISSUE THREAD

**Issue by joha1** [bcl/digitemp#31]
Issue #28 seems to indicate that buttons that are not explicitly listed might still work.
How do I best test that without causing issues?
Apparently, the documentation with `digitemp -something` is outdated, and it's now `digitemp_DS$number`, but of course none of the three options matches my devices (DS1921H-F5 and DS1922L sensor and DS9490R USB Adapter + MF1402 reader (some custom clamp for custom waterproofed ibuttons)).
According to the docs *Version 3.3.1 works with the DS9490R USB adapter using the DS2490 USB to 1-wire adapter chip* so I suppose I should use `digitemp_DS2490` to talk to my DS9490R?
But just trying  `digitemp_DS2490 -s/USB -i` or with `…s/dev/USB…` according to the manpage fails with 

    Found DS2490 device #1 at 002/007
    USB ERROR: owAcquire called with invalid port string

So it sees the device, but it's missing the port.
What do I need to specify to get started?

**Comment by bcl** [comment]
No slash needed. Use `digitemp_DS2490 -sUSB -w -a` to show all the devices and see if it will read the temperatures.
