### ISSUE TITLE
digitemp_DS2490 not installed?

### ISSUE THREAD

**Issue by GSVNoFixedabode** [bcl/digitemp#34]
On current Ubuntu 22.04 / Jammy
lsusb output: **Bus 001 Device 003: ID 04fa:2490 Dallas Semiconductor DS1490F 2-in-1 Fob, 1-Wire adapter**
/etc/modprobe.d/local-config.conf contents: 
   blacklist w1_smem
   blacklist w1_therm
   blacklist ds2490
   blacklist wire
But only digitemp_9097 and digitemp_9097U installed in /usr/bin with latest release.
Is there an additional package to install?

**Comment by bcl** [comment]
The 1-wire library that digitemp uses (originally from Dallas) only supports the old libusb. Linux distributions have been dropping it recently, so I believe the maintainer decided to only ship the supported binaries. Issue #14 is where work for the new libusb is being tracked -- but I haven't had time to actually do it.
