### ISSUE TITLE
Omnibus patch integration

### ISSUE THREAD

**Issue by rfinnie** [bcl/digitemp#5]
Greetings!

Current Debian packaging includes a number of patches against 3.6.0 -- a full list is at https://github.com/rfinnie/digitemp-pkg-debian/tree/master/patches .  They all have inline patch comments, but in general:

 * banner-version.patch - Already applied in HEAD.
 * code-spelling.patch - Simple spelling corrections caught by lintian (which checks for common misspellings but isn't comprehensive).
 * devlength.patch - Covered by PR #1 .
 * makefile.patch - Allows for CFLAGS and LDFLAGS to be specified (for hardening), also allows for multiple builds for the different digitemp_* binaries in build directories using VPATH.
 * flush-stdout.patch - Already applied in HEAD.
 * format-security.patch - Already applied in HEAD.
 * flock.patch - Replaces lockdev (which is deprecated upstream) with flock - see http://bugs.debian.org/728018 for details.
 * setbaudcom.patch - Fixes SetBaudCOM conflicting parameter types.
 * usb-reset-status.patch - Properly reset the 1-Wire bus on DS2490.  (Seems sane, reported in http://pad.lv/1397382 but I do not have access to a DS2490 to test.)
 * platform.patch - Removes platform-specific handling of getopt optind/eof stuff in favor of a way which is handled platform independently (and allows for other architectures such as Hurd/kFreeBSD which were FTBFSing in Debian).

I'd like to get these applied, but there are several ways to go about it so I'm opening this as an issue to discuss beforehand.  I can submit a PR with a branch that includes all of the commits which aren't already in HEAD, or I could submit individual PRs (though some of the patches depend on previous patches, which would make things a little difficult).  Either way, I would recommend accepting PR #1 first if you could, as it covers an increase which I've missed downstream.

Thank you!

**Comment by bcl** [comment]
Thanks! A branch with all of the new stuff would be just fine.
